[package]
name = "pdf_cj"
version = "0.1.0"
description = "PDF library for Cangjie - OpenPDF equivalent"

cjc-version = "1.0.4"
output-type = "static"

[dependencies]
zlib4cj = { git = "https://gitcode.com/chaoling83/zlib4cj.git" }

[test-dependencies]
