import com.lowagie.text.*;
import com.lowagie.text.pdf.*;
import java.awt.Color;
import java.io.*;
import java.nio.file.*;

public class S10_PageEvent {
    static final String FONT_PATH = "/usr/share/fonts/opentype/noto/NotoSansCJK-Regular.ttc,0";
    static final String IMG_DIR   = "images/";
    static final String OUT_DIR   = "output/";

    static BaseFont CJK_BF;
    static BaseFont HELV_BF;
    static {
        try {
            CJK_BF  = BaseFont.createFont(FONT_PATH, BaseFont.IDENTITY_H, BaseFont.EMBEDDED);
            HELV_BF = BaseFont.createFont(BaseFont.HELVETICA, BaseFont.WINANSI, BaseFont.NOT_EMBEDDED);
        } catch (Exception e) { throw new RuntimeException(e); }
    }
    static Font cjk(float s)     { return new Font(CJK_BF, s); }
    static Font cjkBold(float s) { return new Font(CJK_BF, s, Font.BOLD); }
    static Font helv(float s)    { return new Font(HELV_BF, s); }

    // Custom page event for header/footer using PdfPageEventHelper
    static class HeaderFooterEvent extends PdfPageEventHelper {
        private String documentTitle;

        @Override
        public void onOpenDocument(PdfWriter writer, Document document) {
            documentTitle = "S10: Page Event Demo";
            System.out.println("  [Event] onOpenDocument called");
        }

        @Override
        public void onCloseDocument(PdfWriter writer, Document document) {
            System.out.println("  [Event] onCloseDocument called. Total pages: " + (writer.getPageNumber() - 1));
        }

        @Override
        public void onStartPage(PdfWriter writer, Document document) {
            System.out.println("  [Event] onStartPage: page " + writer.getPageNumber());
        }

        @Override
        public void onEndPage(PdfWriter writer, Document document) {
            PdfContentByte cb = writer.getDirectContent();
            // Draw header
            cb.saveState();
            cb.setColorFill(new Color(50, 50, 150));
            cb.rectangle(36, 810, 522, 20);
            cb.fill();

            cb.beginText();
            cb.setFontAndSize(HELV_BF, 10);
            cb.setColorFill(Color.WHITE);
            cb.setTextMatrix(40, 815);
            cb.showText(documentTitle);
            cb.setTextMatrix(520, 815);
            // Page number aligned right
            String pageStr = "Page " + writer.getPageNumber();
            // approximate right-align
            cb.showTextAligned(PdfContentByte.ALIGN_RIGHT, pageStr, 558, 815, 0);
            cb.endText();

            // Draw footer
            cb.setColorStroke(new Color(150, 150, 150));
            cb.setLineWidth(0.5f);
            cb.moveTo(36, 36);
            cb.lineTo(558, 36);
            cb.stroke();

            cb.beginText();
            cb.setFontAndSize(HELV_BF, 8);
            cb.setColorFill(new Color(100, 100, 100));
            cb.setTextMatrix(36, 25);
            cb.showText("Generated by OpenPDF 2.0.3 — S10 Page Event Demo");
            cb.showTextAligned(PdfContentByte.ALIGN_RIGHT, "Page " + writer.getPageNumber(), 558, 25, 0);
            cb.endText();

            cb.restoreState();
            System.out.println("  [Event] onEndPage: page " + writer.getPageNumber());
        }

        @Override
        public void onChapter(PdfWriter writer, Document document, float paragraphPosition, Paragraph title) {
            System.out.println("  [Event] onChapter: " + title.getContent());
        }

        @Override
        public void onSection(PdfWriter writer, Document document, float paragraphPosition, int depth, Paragraph title) {
            System.out.println("  [Event] onSection depth=" + depth + ": " + title.getContent());
        }
    }

    public static void main(String[] args) throws Exception {
        new File(OUT_DIR).mkdirs();

        Document doc = new Document(PageSize.A4, 72, 72, 90, 60);
        PdfWriter writer = PdfWriter.getInstance(doc, new FileOutputStream(OUT_DIR + "java_s10_pageevent.pdf"));

        // Attach the page event
        writer.setPageEvent(new HeaderFooterEvent());
        doc.open();

        // Main content
        Paragraph titlePara = new Paragraph("S10: Page Event Demo", cjkBold(18));
        titlePara.setAlignment(Element.ALIGN_CENTER);
        titlePara.setSpacingAfter(20);
        doc.add(titlePara);

        doc.add(new Paragraph("This document demonstrates PdfPageEventHelper callbacks.", helv(12)));
        doc.add(new Paragraph("The header shows the document title and page number.", helv(11)));
        doc.add(new Paragraph("The footer shows the generator info and page number.", helv(11)));

        // Chapter 1
        doc.add(new Paragraph("章节一 Chapter 1", cjkBold(14)));
        doc.add(new Paragraph("This is the content of Chapter 1. " +
                "The onChapter callback fires when a Chapter element is added. " +
                "Section callbacks fire for section elements.", helv(11)));

        // Long content to force multiple pages
        String lorem = "The quick brown fox jumps over the lazy dog. " +
                "Pack my box with five dozen liquor jugs. ";
        for (int i = 1; i <= 8; i++) {
            Paragraph p = new Paragraph("Paragraph " + i + ": " + lorem + lorem, helv(11));
            p.setSpacingAfter(8);
            doc.add(p);
        }

        // Force page 2
        doc.newPage();
        doc.add(new Paragraph("章节二 Chapter 2 — Page 2", cjkBold(14)));
        doc.add(new Paragraph("Content of Chapter 2 on page 2.", helv(12)));
        for (int i = 1; i <= 8; i++) {
            doc.add(new Paragraph("Page 2, Para " + i + ": " + lorem, helv(11)));
        }

        // Force page 3
        doc.newPage();
        doc.add(new Paragraph("章节三 Chapter 3 — Page 3", cjkBold(14)));
        doc.add(new Paragraph("Content of Chapter 3 on page 3.", helv(12)));
        doc.add(new Paragraph("CJK text: 这是第三页的中文内容，用于测试页面事件在多页文档中的正常工作。", cjk(12)));

        doc.close();

        System.out.println("S10 done: " + OUT_DIR + "java_s10_pageevent.pdf");
    }
}
